use crate::config::QuartzError;
use crate::state::Vault;
use anchor_lang::prelude::*;

use solana_program::{program::invoke_signed, system_instruction};

#[derive(Accounts)]
pub struct MigrateVault<'info> {

    /// CHECK: This Vault account is checked by the migrate_vault instruction , also needs to be AccountInfo not UncheckedAccount for some reason
    #[account(
        mut,
        seeds = [b"vault".as_ref(), owner.key().as_ref()],
        bump
    )]
    pub vault: AccountInfo<'info>,

    #[account(mut)]
    pub owner: Signer<'info>,

    /// CHECK: This is a lookup table account this will be generated by the migrate_vault instruction
    pub lookup_table: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
}

pub fn migrate_vault_handler(ctx: Context<MigrateVault>) -> Result<()> {
    // Verify the vault owner
    let (vault_owner, vault_bump) = {
        let data = &ctx.accounts.vault.data.borrow();
        let owner_bytes = &data[8..40];
        let owner = Pubkey::new_from_array(owner_bytes.try_into().unwrap());
        (owner, data[40])
    };

    require_keys_eq!(
        vault_owner,
        ctx.accounts.owner.key(),
        QuartzError::InvalidVaultOwner
    );

    let owner = ctx.accounts.owner.key();

    let seeds = &[
        b"vault",
        owner.as_ref(),
        &[vault_bump]
    ];
    let signer_seeds = &[&seeds[..]];

    //TODO: Generate the lookup table account
    
    // create our new data that we want to put into our old account
    let new_vault = Vault {
        owner: ctx.accounts.owner.key(),
        bump: vault_bump,
        spend_balance_amount: 0,
        lookup_table: ctx.accounts.lookup_table.key(),
    };
    let new_vault_vec = new_vault.try_to_vec().unwrap();

    let vault_data_account = &ctx.accounts.vault;

    let new_size = Vault::INIT_SPACE;

    let rent = Rent::get()?;
    let new_minimum_balance = rent.minimum_balance(new_size);

    let lamports_diff = new_minimum_balance
        .checked_sub(vault_data_account.lamports())
        .ok_or(QuartzError::MathOverflow)?;

    let owner = &ctx.accounts.owner;

    invoke_signed(
        &system_instruction::transfer(owner.key, vault_data_account.key, lamports_diff),
        &[
            ctx.accounts.owner.to_account_info(),
            ctx.accounts.vault.to_account_info(),
            ctx.accounts.system_program.to_account_info(),
        ],
        signer_seeds,
    )?;

    // First reallocate the account
    vault_data_account.realloc(new_size, false)?;

    // Then borrow the data to modify it
    let mut vault_data = vault_data_account.try_borrow_mut_data()?;
    vault_data[8..].copy_from_slice(&new_vault_vec[..]);

    Ok(())
}
